import { Roboto } from 'next/font/google';
import "./globals.css";

const roboto = Roboto({
  weight: '400',
  subsets: ['latin']
})

export const metadata = {
  title: "ABC",
  description: "Generated by create next app for ABC",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={roboto.className} data-theme="light">
      <body >{children}</body>
    </html>
  );
}
